{% set version = "15.5" %}
{% set date = "20210820" %}
{% set sha256 = "d933c49c4efe3baa79a4b17e31220e1ac8efa5b4f850123ff782a860bd5b1747" %}

package:
  name: entrez-direct
  version: {{ version }}
    
source:
  url: https://ftp.ncbi.nlm.nih.gov/entrez/entrezdirect/versions/{{ version }}.{{ date }}/edirect.tar.gz
  sha256: {{ sha256 }}
#  patches:
#    - xtract.patch

build:
  noarch: generic
  number: 0

requirements:
  host:
    - perl
  run:
    - perl

test:
  commands:
    - efetch --help
    - epost --help
    - efilter --help
    - einfo --help
    - esearch --help
    - elink --help
    - espell --help
    - enotify --help
    - esummary --help
    - entrez-phrase-search --help
    - xtract -version

about:
  home: https://ftp.ncbi.nlm.nih.gov/entrez/entrezdirect/versions/{{ version }}.{{ date }}/README
  license: PUBLIC DOMAIN
  summary: E-utilities for the NCBI
  description: |
    Entrez Direct (EDirect) is an advanced method for accessing the NCBI's set of interconnected databases (publication,
    sequence, structure, gene, variation, expression, etc.) from a UNIX terminal window. Functions take search terms
    from command-line arguments. Individual operations are combined to build multi-step queries. Record retrieval and
    formatting normally complete the process.

extra:
  container:
    extended-base: True
